### ISSUE TITLE
Création d'un service listant les applications disponibles

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewerstudio#1]
L'objectif est de pouvoir , depuis l'interface du générateur, charger la configuration d'une application publiée sur le serveur (fichier statique) en plus de la possibilité de charger une configuration depuis un fichier local.

**Comment by bchartier** [comment]
Quand tu parles d'applications, il s'agit bien des applications mviewer (pas les applications mviewer studio) ?
A Neogeo nous devons mettre en place ce mécanisme pour datasud :
- lister les cartes de l'organisme auquel l'utilisateur est rattaché
- lister l'ensemble des cartes si l'utilisateur est un admin
Comme la plateforme datasud et celle de GéoBretagne ne sont pas identiques au regard du proxy et de l'authentification nous aurons des différences au niveau de l'implémentation. Mais il faudrait qu'on voie comment faire pour que le code de mviewer ne diverge pas (ou pas trop).

**Comment by bchartier** [comment]
J'ai 2 soucis avec la mise en œuvre de cela pour datasud.

1. Dans un commit que j'ai poussé dans le master de mviewerstudio sur GéoBretagne j'ai fait une modif pour récupérer les informations de l'utilisateur (nom et organisme d'appartenance) via un appel à une URL (user_info) qui n'est pas gérée par les scripts php de mviewerstudio de GéoBretagne. ça devrait donc coincer dans cette version. Si on veut que cette fonction soit aussi dans GéoBretagne il faudrait implémenter ce script et lui donner un nom cohérent par rapport aux autres scripts php.

2. La notion d'organisme vient du fait que dans datasud nous stockons les applications mviewer d'un organisme dans un répertoire qui lui est propre. Or un utilisateur peut avoir des rôles dans plusieurs organismes (contributeur, référent et admin aussi). Un référent a un droit de regard sur toutes les applications d'un organisme. Un contributeur s'occupe de ses propres cartes. Un admin a les mêmes droits qu'un référent mais pour tous les organismes. Du coup, un utilisateur doit pouvoir enregistrer une applications dans les répertoires de tous les organismes pour lesquels il est référent ou contributeur. Cela ne change rien au fonctionne de mviewerstudio puisque c'est géré du côté du proxy (les scripts php de mviewerstudio sont remplacés dans le cas de datasud par notre propre proxy pour gérer ces questions liées aux droits des utilisateurs) sauf sur 2 points :
* l'utilisateur dans l'IHM de mviewerstudio doit choisir un organisme parmi ceux auxquels il est rattaché pour pouvoir limiter les applications qu'il peut ouvrir et modifier. Pour l'instant, ma vision des choses c'est que si user_info indiquent que l'utilisateurs est associé à plusieurs organismes alors une fenêtre modale apparaît pour lui demander d'en choisir un. Sinon, aucune fenêtre modale n'apparaît. Cela ne devrait quasiment pas avoir d'impact sur GéoBretagne si la notion d'organisme n'est pas utilisée.
* quand on enregistre l'application sur le serveur, il faut spécifier au serveur dans quel répertoire ça doit se faire. ça demande une modification du script store.php. Aujourd'hui se script ne prend en entrée que le fichier de config mais il faudrait que je puisse également spécifier le répertoire de destination.

Pour l'instant, dans mon code, la notion d'organisme porte le nom de "groupe" pour que ce soit aussi adaptable que possible à n'importe qu'elle gestion des utilisateurs.

@spelhate : j'espère que tu auras un peu de temps pour qu'on discute de cela ensemble.

**Comment by bchartier** [comment]
> Pour l'instant, dans mon code, la notion d'organisme porte le nom de "groupe" pour que ce soit aussi adaptable que possible à n'importe qu'elle gestion des utilisateurs.

Du coup, pour le script store.php, l'autre paramètre à fournir serait le nom du groupe. Charge ensuite au proxy d'enregistrer le fichier dans le bon répertoire, dans une base ou je ne sais quoi.

**Comment by bchartier** [comment]
> * quand on enregistre l'application sur le serveur, il faut spécifier au serveur dans quel répertoire ça doit se faire. ça demande une modification du script store.php. Aujourd'hui se script ne prend en entrée que le fichier de config mais il faudrait que je puisse également spécifier le répertoire de destination.

J'ai adopté une autre stratégie : je renseigne dans la balise dc:publisher le nom du groupe/organisme que l'utilisateur avait retenu. J'utilise donc creator pour l'utilisateur qui crée la carte et publisher pour l'organisme auquel il contribue. Cela me paraît assez naturel et ça évite de devoir toucher à l'interface de store.php.

**Comment by spelhate** [comment]
Ok.

**Comment by bchartier** [comment]
@spelhate : je ne suis pas sûr que cette discussion soit close. Est-ce qu'on a répondu à ton besoin initial ?

**Comment by spelhate** [comment]
> @spelhate : je ne suis pas sûr que cette discussion soit close. Est-ce qu'on a répondu à ton besoin initial ?

Oui. je ferme.
