### ISSUE TITLE
localisation du fichier d'aide html

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewerstudio#106]
Dans l'onglet "application", on peut définir le chemin vers le fichier html qui s'affiche au démarrage du mviewer. Mais où l'utilisateur peut-il stocker un tel fichier ? Dans mon cas, mviewerstudio est intégré à une instance georchestra, dans un container docker. J'imagine que cela joue sur les emplacements possibles ? (même question pour les template mustache d'une couche, où l'on peut préciser où est stocké le fichier .mst)

Vincent

**Comment by bchartier** [comment]
> Dans l'onglet "application", on peut définir le chemin vers le fichier html qui s'affiche au démarrage du mviewer. Mais où l'utilisateur peut-il stocker un tel fichier ?

En général ce type de fichier est stocké au même endroit que le fichier .xml qui constitue la configuration d'une carte/application mviewer. Typiquement, ces fichiers sont stockés dans le répertoire `apps` fourni avec mviewer. Cela devrait ressembler au contenu du répertoire `demo` qui vient également avec le code source de mviewer :
https://github.com/geobretagne/mviewer/tree/master/demo

Typiquement pour la démo cadastre on a cela dans le fichier XML :
https://github.com/geobretagne/mviewer/blob/master/demo/cadastre.xml#L3
`help="demo/demo_cadastre_help.html"`
Il s'agit du chemin relatif au fichier index.html de mviewer.

> Dans mon cas, mviewerstudio est intégré à une instance georchestra, dans un container docker. J'imagine que cela joue sur les emplacements possibles ? (même question pour les template mustache d'une couche, où l'on peut préciser où est stocké le fichier .mst)

En fait, je pense que dans ton cas (je n'ai pas la visibilité sur la configuration technique de ton mviewerstudio) mviewerstudio a été configuré pour déposer automatiquement le fichier XML qu'il crée directement dans l'arborescence de mviewer (ou dans un répertoire auquel mviewer a accès via un lien symbolique ce qui revient au même). Comme mviewer n'a aucun composant s'exécutant côté serveur (html, css, js uniquement), contrairement à mviewerstudio, je pense que tu devrais avoir accès au répertoire qui contient les fichiers créés par mviewerstudio. Dans la configuration par défaut de l'image Docker de mviewer le répertoire `apps` est accessible dans un "volume" Docker :

https://github.com/geobretagne/mviewer/blob/master/Dockerfile#L3
`VOLUME ["/usr/share/nginx/html/apps"]`

Il faut juste que tu voies si tu y as bien accès dans le cas du déploiement réalisé par ton prestataire.

Le fichier index.html de mviewer est juste dans le répertoire parent.
Du coup, si tu as un fichier `aide.html` que tu déposes dans `apps/app-exemple` le chemin que tu devrais renseigner dans mviewerstudio devrait être `apps/app-exemple/aide.html`

**Comment by vfabry** [comment]
OK, je vais demander à mon presta, car je ne vois pas, dans le répertoire apps de mviewer, les xml générés par mviewerstudio.
Merci pour la réponse détaillée !
Vincent

**Comment by bchartier** [comment]
Tu peux déjà regarder s'il y a une différence entre l'URL de l'application/carte par défaut de ton mviewer et celle qui de l'application que tu crées avec mviewerstudio. Quand tu ouvres la carte produite avec mviewerstudio il renseigne l'url avec comme paramètre le chemin vers la nouvelle carte. Cela pourra te donner un indice sur l'emplacement des cartes crées avec mviewerstudio.

**Comment by vfabry** [comment]
oui, il y a une différence : 
* carte générée par mviewerstudio : https://www.geo2france.fr/mviewer/#store/dea4f2a9f7bbb02976f4d93e7e0d4927
* carte mviewer "à la main" : https://www.geo2france.fr/mviewer/?config=apps/sambre_avesnois_thierache.xml#

**Comment by bchartier** [comment]
Ok, il faut que je regarde à quoi fois référence "#store" pour mviewer...
Nous vous remercions de bien vouloir nous excuser pour le délai de notre réponse...

**Comment by bchartier** [comment]
> Ok, il faut que je regarde à quoi fait référence "#store" pour mviewer...

Il s'agit simplement d'un répertoire `store` qui doit se trouver au même niveau que `apps`.
Tu vois un répertoire `store` ?

**Comment by vfabry** [comment]
non
![image](https://user-images.githubusercontent.com/15424976/114201384-6bd09100-9956-11eb-8768-5f60b0593c62.png)

**Comment by bchartier** [comment]
Faudrait demander aux administrateurs de la plateforme si tu peux avoir accès à ce répertoire store.

**Comment by vfabry** [comment]
oui, c'est ce que je vais faire. Merci Benjamin !
