### ISSUE TITLE
centre et niveau de zoom

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewerstudio#107]
Est-ce qu'on peut préciser quelque part dans mviewerstudio le centre de la carte et le niveau de zoom au lancement de l'appli ?
VIncent

**Comment by spelhate** [comment]
Oui c'est ici : https://github.com/geobretagne/mviewerstudio/blob/009d80646b02d6a842e2d424042430279e1386b8/config-sample.json#L24-L26

**Comment by vfabry** [comment]
ok, du coup c'est réglé "une fois pour toute" par l'admin de mviewerstudio, si je comprends bien. L'utilisateur de mviewerstudio ne peut pas le changer pour faire sa carte ?

**Comment by spelhate** [comment]
Le fichier json permet de configurer la carte au démarrage de mviewerstudio.
Ainsi la carte est centrée par défaut sur les Hauts-de-France.
L'utilisateur a ensuite la possibilité de zoomer et de se déplacer dans la carte pour "construire" le cadrage initial de son application mviewer.

**Comment by spelhate** [comment]
J'en déduis que la fonctionnalité du cadrage de la carte n'est pas très intuitive ;-)

**Comment by vfabry** [comment]
Ah OK ! (non mais c'est moi qui suis fatigué :-) )
