### ISSUE TITLE
Branch developp : suppression ?

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewerstudio#111]
Salut à tous,

Vu dans les commentaires de la PR [#110] d'Hannah.

Branche créé par erreur. Si je la supprime il n'y aura pas d'effets de bords ?

**Comment by bchartier** [comment]
Salut,
Visiblement `developp` a été mergé dans `master`.
Donc les commits de `developp `ne seront pas perdus. Donc tu peux supprimer developp.

Mais comme les commits spécifiques de `developp` ne sont pas passés par `develop` on risque d'avoir un petit peu de boulot pour réintégrer les commits en question dans `develop` (gestion de conflits à régler ou des cherrypick j'imagine... à voir).

**Comment by bchartier** [comment]
Après la suppression de cette branche il faudra mettre au carré les deux branches develop et master. Donc soit on laisse ouvert le présent ticket, soit on en crée un autre spécifiquement pour la remise au carré.

**Comment by lecault** [comment]
Du coup il faut récupérer les commits avant suppression ou on verra après en partant du master ?

Pour la mise au carré c'est pour moi une autre issue.

**Comment by bchartier** [comment]
On récupère les commits après. Avec master et develop on arrivera à le faire.
Ok pour faire un autre ticket.

**Comment by lecault** [comment]
Fait
