### ISSUE TITLE
Erreur build image docker

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#120]
Nous avons de nouveau des erreurs de build des images docker (qui sont construites automatiquement avec des github actions).
L'erreur intervient au moment de la réalisation des tests unitaires sur le backend Python :

```
mviewerstudio_backend/test.py ....F....                                  [100%]

=================================== FAILURES ===================================
______________________ TestStoreMviewerConfig.test_store _______________________

self = <python.mviewerstudio_backend.test.TestStoreMviewerConfig object at 0x7f7d9f453b50>
client = <FlaskClient <Flask 'mviewerstudio'>>
header_client1 = {'sec-firstname': 'baz', 'sec-lastname': 'baf', 'sec-org': 'bar', 'sec-roles': 'USER;SUPERUSER', ...}

    def test_store(self, client, header_client1):
        client_data = test_xml.format(
            title="test_store1", creator="test_user", publisher="test_publisher"
        )
        filehash = hashlib.md5()
        filehash.update(client_data.encode("utf-8"))
        filehash = filehash.hexdigest()
        p = client.post("/srv/store", data=client_data, headers=header_client1)
        assert p.status_code == 200
        assert p.json == {"filepath": f"{filehash}.xml", "success": True}
        assert len(os.listdir("./store")) == 2
>       assert os.listdir("./store")[0] == f"{filehash}.xml"
E       AssertionError: assert 'styles' == 'e5d553ba0eb2...752db88a1.xml'
E         - e5d553ba0eb2ec50b310d3a752db88a1.xml
E         + styles

mviewerstudio_backend/test.py:156: AssertionError
=========================== short test summary info ============================
FAILED mviewerstudio_backend/test.py::TestStoreMviewerConfig::test_store - As...
========================= 1 failed, 8 passed in 0.44s ==========================
Error: Process completed with exit code 1.
```

Ce type d'erreur avait déjà été signalé par le passé : #103

**Comment by spelhate** [comment]
En regardant de plus près, ce qui fait planter le test, c'est la présence d'un répertoire nommé styles dans le dossier store.
Je ne sais pas d'où vient ce dossier. C'est la commande test.py qui le génère.

**Comment by bchartier** [comment]
> En regardant de plus près, ce qui fait planter le test, c'est la présence d'un répertoire nommé styles dans le dossier store.
> Je ne sais pas d'où vient ce dossier. C'est la commande test.py qui le génère.

Ah, oui. Le test s'attend à trouver un fichier `e5d553ba0eb2ec50b310d3a752db88a1.xml` mais trouve un répertoire nommé `styles`.

Les fonctions de test utilise la fixture `cleandir` pour nettoyer le répertoire après l'exécution de chaque test : utilisation de [rmtree](https://docs.python.org/3.7/library/shutil.html#shutil.rmtree) après le `yield`. `yield` sépare le code qui est exécuté au moment de la préparation du test du code qui est exécuté pour le nettoyage. J'ai l'impression qu'il n'y a pas de préparation du répertoire. Le sous répertoire `styles` est donc là avant l'exécution du test `TestStoreMviewerConfig`.

En parcourant le code je trouve des références à ce sous-répertoire là dans `route.py` :
- https://github.com/geobretagne/mviewerstudio/blob/develop/srv/python/mviewerstudio_backend/route.py#L24
- https://github.com/geobretagne/mviewerstudio/blob/develop/srv/python/mviewerstudio_backend/route.py#L112

**Comment by bchartier** [comment]
> C'est la commande test.py qui le génère.

C'est plutôt à l'initialisation de blueprint Flask `basic-store` que ce répertoire est créé. Il est donc là tout le temps (à chaque fois qu'on lance l'appli je pense (que ce soit pour exécuter les tests unitaires ou autre chose). Ne me demande pas ce qu'est un blueprint Flask (c'est flou pour moi - c'est une sorte de modularisation du code d'une appli Flask).
Sauf que les tests doivent le supprimer systématiquement après chaque test utilisant le fixture `cleandir`.

Je n'ai pas encore compris à quoi sert ce répertoire "styles". J'ai juste le sentiment qu'il est destiné à copier des styles qui sont déclarés dans l'application/carte faite avec mviewer.

**Comment by bchartier** [comment]
Le truc pourri c'est que le test considère que le premier truc qui doit être listé dans l'inventaire du répertoire `store` c'est le fichier que xml qui a été envoyé par une requête post. Or il trouve en premier le répertoire `styles`.
On peut modifier le code du test pour qu'il vérifie juste que le fichier en question est bien présent sans se préoccuper de savoir s'il est retourné en première position (`os.listdir("./store")[0]`) ou deuxième position dans l'inventaire du répertoire `store`.

Du coup ça pourrait donner cela :
`assert os.path.exists(f"{filehash}.xml") in listdir("./store")`
ou
`assert f"{filehash}.xml" in os.listdir("./store")`

**Comment by bchartier** [comment]
@spelhate :
J'ai juste à faire un commit dans la branche `develop` pour que le workflow des github actions soit relancé et qu'on sache si ça corrige bien le truc ?

**Comment by bchartier** [comment]
Et hop, c'est fait.
Tata !

Sinon, faudrait peut-être lancer le build d'une image docker que sur master, non ?
Faudrait peut-être aussi documenter cette histoire de répertoire styles

**Comment by spelhate** [comment]
Merci @bchartier 
Pour les styles, je ne connais pas le cas d'usage. la documentation doit être faite réalisée par celui ou celle qui implémente l'évolution.

**Comment by spelhate** [comment]
Par contre les images ne sont pas "pushées" sur le hub docker. Je réouvre

**Comment by spelhate** [comment]
Il y a une erreur dans la CI
https://github.com/geobretagne/mviewerstudio/blob/b274cdca9053545dd42c7fa9455ca483b6d1d1a2/.github/workflows/build.yml#L47

Il faut remplacer `mviewer/mviewerstudio` par `geobretagne/mviewerstudio`

**Comment by spelhate** [comment]
Les premières images ont été pushées avec la modification indiquée plus haut.
Mais il y a encore des choses à corriger. Les tags n'ont pas l'air de fonctionner.
![image](https://user-images.githubusercontent.com/1793792/150089577-2ad4d124-4e74-4bf4-bfeb-351d479326e2.png)

**Comment by bchartier** [comment]
Visible c'est le calcul de la variable VERSION qui coince :

**Comment by spelhate** [comment]
C'est corrigé. J'ai utilisé ce qui avait été fait sur mviewer par @RemiDesgrange 
![image](https://user-images.githubusercontent.com/1793792/150094822-fc8664d8-d47c-44ae-a649-89ec7167cb63.png)
