### ISSUE TITLE
Comment ordonner les fonds (baselayers) dans le "backoffice" de Studio ?

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewerstudio#122]
Bonjour,

En préparant une montée de version de Mviewer, on s'est interrogé pour mettre à jour les fonds cartographiques disponibles (et mettre à jour les clés IGN par exemple).
Est- il possible de changer l'ordre des fonds dans l'onglet fonds ?

![image](https://user-images.githubusercontent.com/7600693/152229704-c9c25f02-c35d-4dbc-afe1-68e489d9d29a.png)

D'avance Merci,

Jérôme Boutet

**Comment by lecault** [comment]
Bonjour Jérôme,

L'ordre des fonds est paramétrable dans le config.json au niveau des bases layers : (exemple : https://github.com/geobretagne/mviewerstudio/blob/master/config-sample.json).
Tu créé une copie du config-sample.xml comme indiqué ici https://github.com/geobretagne/mviewerstudio/blob/master/doc/admin.md.

Et pour les clés IGN oui tu peux les y mettre (je suppose que tu fais référence au SCAN25).

**Comment by bchartier** [comment]
@jerbou : dans ton cas, avec Worldline, si je me souviens bien, la config de mviewerstudio fait partie des trucs qui sont gérés au niveau du système de déploiement des paquets. Je ne pense pas que tu puisses le faire en remplaçant un fichier par sFTP par exemple. Il faudrait que tu modifies avec Neogeo le contenu du fichier de config dans le Gitlab et que tu testes sur les environnements de test/dev puis préprod pour ensuite le déployer en prod. Enfin, si je me souviens bien. à voir avec @sebastiendarocha peut-être ?

**Comment by jerbou** [comment]
Merci à vous deux pour les réponses.

@lecault : merci pour le fichier de config. (nous devons effectivement MAJ la cél pour scan25 et autres fonds IGN, notamment enlever feu scan express).

@bchartier quelle mémoire ! nous communiquons les urls, et config de baselayers à ajouter et c'est Neogeo qui fait les modif' dans le fichier de config, tout en respectant le circuit de validation (noprod, recette 1, livraison prod, recette finale).

Avec toutes l'ensemble de votre retour, on peut donc modifier tout cela.

Merci !
