### ISSUE TITLE
Ajout dans le studio de balises complémentaires Mviewer Version 3.4 et =>

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewerstudio#124]
Bonjour,

Nous commençons à voir arriver des utilisations avancées de Mviewer 3.4 (avec du toplayer, exclusive de l'animate dans les searchparameters).

Est-ce qu'il serait possible d'intégrer dans l'ihm de Studio prochaines version l'ensemble de ces balises (Version 3.4, voir supérieur)

D'avance Merci,

jerome boutet
idéobfc

**Comment by lecault** [comment]
Bonjour Jérôme,

Effectivement, il faudra prévoir l'intégration de ces nouvelles fonction dans studio. 
Mais ceci n'est pas encore prévu, nous envisageons pour cette année une refonte du parcours utilisateur et quelques débugages avant l'ajout de nouvelles fonctionalités.

Loïc

**Comment by jerbou** [comment]
Merci Loic,

Je voulais "écrire" le besoin qqpart... on fera le planning souhaité / souhaitable / réaliste lors d'autres points PSC :)
Est-ce que l'on maintient le ticket ouvert ou pas ?

jerome

**Comment by lecault** [comment]
Oui on laisse ouvert

**Comment by lecault** [comment]
Prévu dans le marché Megalis je ferme l'issue
