### ISSUE TITLE
Module « Application »

### ISSUE THREAD

**Issue by Agath21** [geobretagne/mviewerstudio#134]
# Module « Application » : Paramètres globaux du mviewer et couches de fonds

## Description 
Ce module permet de configurer globalement son application en activant les options et en indiquant certaines informations : 

![4](https://user-images.githubusercontent.com/22764056/200796611-974aee6d-3a23-42b5-814a-655005c9cc2a.png)

## Spécifications

- Les fonctionnalités "Page d'accueil", "Recherche", "Fond de plan" sont gérés pas un composant `accordion`
- Le titre de l'application saisi doit s'afficher dans le wizard

## Affichage conditionné (mode avancé)

| Fonctionnalités                                                                           | Mode avancé (masqué par défaut)  |
|-------------------------------------------------------------------------------------------|----------------------------------|
| Titre de l’application                                                                    |                                  |
| Logo                                                                                      |                                  |
| Style                                                                                     |                                  |
| Emprise de la carte                                                                       |                                  |
| Interdire la navigation hors de l'étendue                                                 | x                                |
| Outil de mesure                                                                           |                                  |
| Export de la carte en image                                                               |                                  |
| Affichage des coordonnées au click                                                        | x                                |
| Afficher/masquer toutes les données d'une thématique en un click                          | x                                |
| Page d’accueil                                                                            | x                                |
| Fond de plan                                                                              |                                  |
| Fond de plan – mode d’affichage                                                           | x                                |
| Recherche – Recherche d’adresse                                                           |                                  |
| Recherche – Recherche d’entité                                                            | x                                |

**Comment by Agath21** [comment]
### Avancement des fonctionnalités : 

- [ ] Titre de l’application
- [ ] Logo
- [ ] Style  
- [ ] Emprise de la carte
- [ ] Interdire la navigation hors de l'étendue
- [ ] Outil de mesure 
- [ ] Export de la carte en image
- [ ] Affichage des coordonnées au click
- [ ] Afficher/masquer toutes les données d'une thématique en un click
- [ ] Page d’accueil 
- [ ] Fond de plan
- [ ] Fond de plan – mode d’affichage
- [ ] Fond de plan – par défaut
- [ ] Recherche – Recherche d’adresse              
- [ ] Recherche – Recherche d’entité

**Comment by bchartier** [comment]
Quelques commentaires sur la copie d'écran présente dans la description du ticket :
* Je trouve que la rubrique "Application" est très grande (trop de choses dedans : titre, description, fond de carte, localisation par défaut, fonctionnalités...)
* Les fonctionnalités sont réparties à plusieurs endroits : la liste des fonctionnalités sous le lien vers le logo et puis la configuration de quelques fonctionnalités tout en bas (recherche et page d'accueil). Il faudrait mieux les regrouper selon moi.
* J'aurais tendance à remplacer l'entrée "Application" en plusieurs :
  * Identité visuelle : titre, description, logo, thème et peut-être aussi la popup d'accueil
  * Carte : étendue, zoom et fonds de carte
  * Fonctionnalités : activation des différents outils et paramétrage de la recherche
* On a la notion de "avancé" à deux endroits : à gauche dans les fonctionnalités avancés et en haut à droite avec l'interrupteur qui permet d'activer l'interface avancée. C'est plutôt déroutant.
* J'aurais tendance à simplifier "Thématiques et données" en "Données"
