### ISSUE TITLE
Checkbox très grande pour l'activation de la recherche

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#14]
Je me demande pourquoi la checkbox d'activation de la recherche est si grosse :
```
.checkbox.lg input[type=checkbox] {
    transform: scale(2);
    margin-left: -30px!important;
}
```

Est-ce volontaire ?

**Comment by spelhate** [comment]
Un délire de développeur probablement.

**Comment by bchartier** [comment]
j'ai l'impression que c'est corrigé.
