### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewerstudio#16]
@spelhate : est-ce que tu saurais m'expliquer en quelques mots l'utilisation du proxy ?
Il faut que j'en installe un sur le serveur qui héberge mviewer/mviewer studio (qui n'est pas un serveur georchestra) ?

Vincent Fabry
GéoPicardie

**Comment by spelhate** [comment]
Le proxy est un service mandataire qui permet de contourner certaines restrictions liées à Javascript.
En principe une application javascript (mviewer par exemple) ne peut pas dialoguer avec des serveurs étrangers (nom de domaine différent du domaine hébergeant l'application).
Par essence, le mapfishapp de géopicardie ne peut pas questionner le catalogue de GéoBretagne.
Il existe plusieurs moyens de contourner cette restriction. En voici 2

- activer [CORS](https://enable-cors.org/)  sur le(s) serveur(s) distant(s). C'est le cas sur GéoBretagne. On ne peut pas le faire pour des serveurs que l'on n'administre pas.
- utiliser un proxy qui fera les requêtes pour le compte de l'application.

Si tu souhaites utiliser mviewerstudio avec une plateforme que tu maîtrises, activer CORS sur cette plateforme sera suffisant. Si tu souhaites travaillers avec plusieurs plateformes, il te faudra installer un proxy.

**Comment by vfabry** [comment]
Merci Sébastien, c'est très clair ! (et bonne chance pour ce soir)
