### ISSUE TITLE
Bug critique depuis dernière PR

### ISSUE THREAD

**Issue by spelhate** [geobretagne/mviewerstudio#27]
Depuis le merge de la dernière PR, les fichiers javascripts `mv.js` et `mviewerstudio.js` sont en erreur.
Dans les 2 cas , il manque une accolade fermante.

**Comment by bchartier** [comment]
Ça sent la bourde qui vient de chez moi ça. Désolé.

**Comment by spelhate** [comment]
Ce n'est pas grave car détecté et fixé rapidement. C'est vrai que le risque d'erreur est plus grand sur des PR qui embarquent de nombreux commits.
