### ISSUE TITLE
GetLegend graphic et URL avec ?

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewerstudio#29]
[Régression]
Ajout d'une couche provenant du serveur suivant : 
http://geolittoral.din.developpement-durable.gouv.fr/wxs

La couche s'affiche correctement mais la légende n'est pas visible.

=> Le problème provient de l'URL renseignée automatiquement dans le XML : http://geolittoral.din.developpement-durable.gouv.fr/wxs?language=fre&

Voici le GetLegendGraphic généré : 
http://geolittoral.din.developpement-durable.gouv.fr/wxs?language=fre&?service=WMS&Version=1.3.0&request=GetLegendGraphic&SLD_VERSION=1.1.0&format=image%2Fpng&width=30&height=20&layer=n_nature_cote_l&style=default&legend_options=fontName:Open%20Sans;fontAntiAliasing:true;fontColor:0x777777;fontSize:10;dpi:96&TRANSPARENT=true

=> Pour résoudre le soucis, il faut enlever a partir du ? : http://geolittoral.din.developpement-durable.gouv.fr/wxs

Voici le GetLegendGraphic corrigé : http://geolittoral.din.developpement-durable.gouv.fr/wxs?service=WMS&Version=1.3.0&request=GetLegendGraphic&SLD_VERSION=1.1.0&format=image%2Fpng&width=30&height=20&layer=n_nature_cote_l&style=default&legend_options=fontName:Open%20Sans;fontAntiAliasing:true;fontColor:0x777777;fontSize:10;dpi:96&TRANSPARENT=true

**Comment by bchartier** [comment]
Ce n'est pas trop la présence de language= dans l'URL qui pose problème mais la présence de 2 points d'interrogation. A mon avis c'est une régression qui fait suite à une mes modifications qui visait à rendre les requêtes envoyées compatibles avec MapServer. Je regarde cela.

**Comment by bchartier** [comment]
Avec ma version (un peu spéciale de mviewerstudio) et mon mviewer, je n'arrive pas à reproduire cela.

En cherchant dans le code, je trouve deux choses :
- dans mviewerstudio, la fonction suivante qui récupère l'URL des légendes si elles sont disponibles dans le GetCapabilities du service :
https://github.com/geobretagne/mviewerstudio/blob/master/lib/ogc.js#L210-L222
- dans mviewer, la fonction suivante qui construit l'URL en dynamique pour récupérer la légende :
https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L325-L354

J'ai plutôt l'impression que ton problème viendrait de mviewer plutôt que mviewer.
Tu confirmes ?

**Comment by bchartier** [comment]
@lecault : est-ce que tu aurais une version en ligne où je pourrais constater le souci ?

**Comment by lecault** [comment]
Sur le studio de GéoBretagne : https://geobretagne.fr/mviewerstudio/
Utilise le compte de demo 
user : demo
mdp : demodemo

**Comment by bchartier** [comment]
Visiblement dans le déploiement sur le serveur de démo de GéoBretagne mviewer n'est pas à jour.
Il manque cette ligne de code :
https://github.com/geobretagne/mviewer/blob/master/js/mviewer.js#L331
Est-ce que tu peux mettre à jour mviewer sur ce serveur ?

**Comment by lecault** [comment]
J'ai mis à jour le mviewer en ajoutant la ligne puis redémarré apache, rien n'a changé.
Je ne vois pas le rapport avec mviewer ?

**Comment by bchartier** [comment]
> J'ai mis à jour le mviewer en ajoutant la ligne puis redémarré apache, rien n'a changé.

La ligne en question est juste le signe que ce n'est pas la bonne version.
Toute la fonction est différente et il est probable que plusieurs commits soient manquant sur le serveur.

> Je ne vois pas le rapport avec mviewer ?

Dans le mviewerstudio de démo de GéoBretagne la légende s'affiche correctement.
Dans le mviewer de démo de GéoBretagne la légende ne s'affiche pas.
Quand je regarde le code de la fonction _getlegendurl de mviewer qui est sur le serveur de démo de GéoBretagne je constate qu'il y a un sérieux écart avec la branche master de mviewer du repo github de GéoBretagne.
Avant de conclure quoi que ce soit sur l'origine de l'anomalie, je pense qu'il faut mettre à jour la version de mviewer du serveur de démo de GéoBretagne.

**Comment by lecault** [comment]
Ok merci, je préfère attendre que Sebastien revienne pour faire un git pull.

**Comment by spelhate** [comment]
Je clos car la mise à jour a corrigé le problème.
