### ISSUE TITLE
Gestion des applications par utilisateurs

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewerstudio#3]
Actuellement à chaque fois que l'utilisateur clic sur prévisualiser, une nouvelle application est créée.
C'est le même principe que le visualiseur GeOrchestra.

**Je trouverai intéressant que l'user puisse supprimer ces anciennes applications.**

_J'aurai aimé qu'en cliquant sur Prévisualiser, on conserve l'application précédent mais ce n'est pas envisageable à court terme : il faudrait pour cela revoir tout le mécanisme._

**Comment by spelhate** [comment]
Done.
