### ISSUE TITLE
Adding new WMS provider

### ISSUE THREAD

**Issue by Ailurupoda** [geobretagne/mviewerstudio#37]
Hi,

I'm trying to use mviewer  studio and i wish to add a new provider. It is a WMS URL from QgisServer. The data is correctly displayed in QGIS, and in the web.

When i try to search a layer from that provider, it doesn't work and i have an error "GetCapability Request error : Not Found".

I installed the mViewerStudio by downloading the zip repository, renaming config-sample to config.xml. An put it on my apache server. 

Do you have any idea why it is acting like that ?

Thanks,

**Comment by bchartier** [comment]
Hi,
Could you share with us the URL of this QGIS Server WMS service in order to be able to see what happens?

**Comment by Ailurupoda** [comment]
I'm using a local URL : `localhost:8888/index.php/lizmap/service/?repository=repo_test&project=projet_test&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities`.

So you won't be able to see what's in the URL :/

**Comment by bchartier** [comment]
The search function parses the content of the WMS capabilities doc.
In order to diagnose your trouble I would need a copy of the GetCapabilities response sent by QGIS server to mviewer. Could you share the capabilities xml doc of your server?

**Comment by Ailurupoda** [comment]
Here is an xml GetCapabilities from our QgisServer.
[qgis_server_wms_capabilities.zip](https://github.com/geobretagne/mviewerstudio/files/3739834/qgis_server_wms_capabilities.zip)


I'm trying to add layers directly in mViewer (without using studio). And i don't manage to get the visual of the data.

I think i don't understand which URL exactly i need to use and how to point the layer.
For example i'm trying :
 ```
  <layer 
                id="Departement_2013" 
                name="Départements" 
                type="wms" 
                url="localhost:8080/index.php/lizmap/service/?repository=001&amp;project=ocs_lizmap&amp;" 
                visible="true" 
                infoformat="text/html" 
                queryable="true">
            </layer>
```
I get the display/undisplay button, the legend is set to unknown and no data shows up.

Do you have any idea ?
Thanks

**Comment by spelhate** [comment]
> Hi,
> I'm working with Ailurupoda and facing the same problem.
> the address (http://services.sandre.eaufrance.fr/geo/zonage?REQUEST=getCapabilities&service=WMS)
> is working in http://kartenn.region-bretagne.fr/mviewerstudio/?xml=#
> when trying in http://localhost/mviewerstudio/# we got "GetCapability Request error : Not Found".
> I join the config.json file in case of.
> Thanks,
> [config.zip](https://github.com/geobretagne/mviewerstudio/files/3738509/config.zip)

I think it's due to lack of localhost/proxy/ . In fact proxy is tetted in config.json.
Do you have ajax proxy in your environnement ?

**Comment by Ailurupoda** [comment]
We don't use any proxy on our environment. Is it imperatively needed ?

**Comment by spelhate** [comment]
It's only needed with servers from other origin if the remote server does not deliver cors headers.

**Comment by spelhate** [comment]
For more details about ajax proxy and cors : https://github.com/geobretagne/mviewer#proxy
