### ISSUE TITLE
Flask Backend 

### ISSUE THREAD

**Issue by fvanderbiest** [geobretagne/mviewerstudio#38]
Erroneously proposed at first on https://github.com/geobretagne/mviewer/issues/166
Any hints, advices before we start working on it ?

**Comment by pierrejego** [comment]
What are you going to do exactly ? Migrate all existing PHP  ? have you some new feature to add ?

**Comment by fvanderbiest** [comment]
No new features, just porting it to python/flask.

**Comment by pierrejego** [comment]
Hi, I had a discussion this week-end about Flask. It seems like there are less hosting possibilities.  For example no simple hosting for OVH or 1and1.  
For example I have a test instance on a simple webhosting OVH ( no ssh access, only ftp) and I can't install Flask even Python. For my case, it's not really a problem, I can change server, but I was thinking about other people's integration.

I am afraid that using Flask will complicate deployment for new comers.  

I am sure Flask is a good Idea, but it's probably to early for this project no ?

**Comment by fvanderbiest** [comment]
Maybe we can separate the back and the front, and leave people the choice of the backend.

**Comment by pierrejego** [comment]
Yes It could be a solution, there is a risk to double work, but it's a good idea.  
@spelhate @bchartier what do you think about it ?

**Comment by spelhate** [comment]
I think it's too  hard to maintain 2 backends. I prefer to choose one (flask is a good idea).
For mviewer it's essential that simple webhosting works. For mviewerstudio, i think this is not a problem.

**Comment by pierrejego** [comment]
Ok so, go for Flask :)

**Comment by bchartier** [comment]
> Yes It could be a solution, there is a risk to double work, but it's a good idea.
> @spelhate @bchartier what do you think about it ?

We (at Neogeo) already maintain a Flask backend for mviewerstudio (we do not use the php scripts).

**Comment by fvanderbiest** [comment]
Thanks, we'll have a look at https://github.com/neogeo-technologies/idgo-mviewerstudio-proxy

**Comment by bchartier** [comment]
This is not our masterpiece. Be indulgent.

**Comment by RemiDesgrange** [comment]
see PR #47

**Comment by RemiDesgrange** [comment]
(maybe we can close this issue)
