### ISSUE TITLE
Docker image & composition

### ISSUE THREAD

**Issue by fvanderbiest** [geobretagne/mviewerstudio#39]
Once #38 is done, we'll contribute a Dockerfile & docker-compose.yml file.

The resulting image should be built on each commit (eg with docker hub or github actions), but to achieve this, we might need help from someone with admin rights on the repo.

**Comment by RemiDesgrange** [comment]
see PR #47

**Comment by RemiDesgrange** [comment]
I think we can close this ?

**Comment by spelhate** [comment]
Ok.
