### ISSUE TITLE
Ajouter le fond IGN

### ISSUE THREAD

**Issue by lecault** [geobretagne/mviewerstudio#4]
Suite à demande du SDIS29, il est intéressant d'ajouter dans les couches de fond de l'IGN.

Exemple celui de GéoBretagne : 

`<baselayer visible="true" id="scan2" thumbgallery="img/basemap/scan.jpg" title="GéoBretagne" label="Cartes IGN" type="WMS" url="https://geobretagne.fr/geoserver/ign/wms" layers="ign_scan" format="image/png" attribution="IGN. Données : IGN SCAN 25®, SCAN REGIONAL®, SCAN 1000® proposés selon la résolution d'affichage. Le SCAN 25® est l’image numérique continue sur tout le territoire français des cartes IGN au 1 : 25 000, cartes reconnues pour leur richesse topographique et leur représentation exemplaire du terrain.</a>"/>
`

**Comment by spelhate** [comment]
Done.
