### ISSUE TITLE
Impossible de sauvegarde le ficher de configuration lors de la prévisualisation

### ISSUE THREAD

**Issue by gryckelynck** [geobretagne/mviewerstudio#42]
Lorsque je clique sur "Prévisualiser" j'ai une erreur qui m'indique que je ne peux pas sauvegarder le fichier de configuration.
Dans la console, j'ai le message suivant:

> Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/tools/mviewerstudio-master/srv/who.php:32) in /var/www/html/tools/mviewerstudio-master/srv/store.php on line 11
> {"success":true, "filepath":"dc0aac848cbbcd18416cc9f7d3b517b8.xml"}

Après analyse, je propose de supprimer la définition du header à la ligne https://github.com/geobretagne/mviewerstudio/blob/master/srv/who.php#L2

et par la même occasion le `?>` en fin de fichier puisque `who.php` est une bibliothèque de fonction qui a vocation à être inclus dans un autre fichier et non un script autonome

**Comment by spelhate** [comment]
Et avec les modifications mentionnées, ça fonctionne ?

**Comment by gryckelynck** [comment]
Oui. Je suis d'ailleurs surpris d'être le seul à rencontrer le problème.
Sans doute une question de configuration de PHP.

**Comment by bchartier** [comment]
@gryckelynck :
Pour information, les déploiements effectués par Neogeo n'utilisent pas les scripts PHP. Nous utilisons un proxy écrit en Python avec Flask pour faire cela. Camptocamp travaille à réaliser quelque chose d'équivalent en Flask également. Cela explique pourquoi une partie des utilisateurs ne rencontrent pas ton problème.

@spelhate :
Est-ce que tu as la possiblité de vérifier le bon fonctionnement de la modif de @gryckelynck ? Ou est-ce qu'on lui demande de faire un pull request pour tester ?

**Comment by spelhate** [comment]
Je viens de tester chez moi.

Ok pour la suppression du `?>` de fin dans le` who.php`.
Par contre, en supprimant la ligne : https://github.com/geobretagne/mviewerstudio/blob/master/srv/who.php#L2 , ca fait planter mviewerstudio ici : https://github.com/geobretagne/mviewerstudio/blob/master/lib/mv.js#L1113 car le type mime de la réponse su serveur est `text/html` au lieu de `application/json;charset=utf-8`

On pourrait éventuellement patcher mviewerstudio, pour forcer le content Type de la réponse du serveur.
Je ne suis pas un spécialiste de php. Vivement l'arrivée d'un backend en flask !

**Comment by fvanderbiest** [comment]
> Vivement l'arrivée d'un backend en flask !

@RemiDesgrange a commencé à travailler dessus, mais je ne vois pas encore de branche sur https://github.com/geobretagne/mviewerstudio/network -> ça va venir !

**Comment by gryckelynck** [comment]
@spelhate, étrange, chez moi ça fonctionne... 
Sans être spécialiste de PHP, définir le header dans who.php ne me semble pas une bonne chose puisqu'il s'agit d'un bibliothèque de fonctions.
Le header devrait normalement être définit au moment de l'envoie de la réponse uniquement (donc 1 seule fois). C'est d'ailleurs bien le cas:
ici: https://github.com/geobretagne/mviewerstudio/blob/master/srv/store.php#L10
et ici: https://github.com/geobretagne/mviewerstudio/blob/master/srv/list.php#L36...
A noter que j'utilise de préférence la ligne suivante pour définir le header: `header('Content-type: application/json; charset=utf-8', true);` mais que cela n'a pas d'impact.

**Comment by jeanpommier** [comment]
Je confirme, j'ai le même problème que @gryckelynck, problème résolu par la solution qu'il propose. Et supprimer la ligne 2 de who.php ne semble pas causer de souci, pour autant que je puisse en juger.
Pour ceux qui voudraient tester, je teste actuellement mviewerstudio _master_ avec un conteneur docker pour php, commande suivante : 
`
docker run --name php --rm -v ~/dev/sk/mviewer-docker:/var/www/html -p 81:80 php:7-apache
`
Avec un config.xml très proche du sample. Ca devrait donc être assez facile à reproduire.

**Comment by spelhate** [comment]
Merci pour la commande docker que je ne connaissais pas. Je retiens votre suggestion de modification des fichiers php. Je pense que le comportement des scripts diffèrent selon la version de php. Il me semble, que les scripts d'origine ont été écrits en php 5.x.
Pouvez-vous faire une PR ? Merci.

**Comment by jeanpommier** [comment]
Ca vaudrait le coup de vérifier les questions de compatibilité et les documenter, du coup, non ?

Je ferai un test rapide php5 vs php7 pour voir. Mais je débute tout juste avec mviewerstudio, il y a encore des trucs qui ne marchent pas dans ma config et que je ne sais pas si c'est un pb de config ou de compatibilité. Donc je vais prendre un peu de temps avant de faire une PR (à moins que @gryckelynck ne me prenne de vitesse ;o), histoire d'être s^ur de ce que je propose

**Comment by spelhate** [comment]
Ok. dans les choses à vérifier : 

- l'utilisateur apache (www-data) dispose des droits d'écriture sur le dossier ciblé par le paramètre de conf **export_conf_folder**

**Comment by bchartier** [comment]
@jeanpommier, @spelhate :
Est-ce que ce ticket doit être fermé ou est-ce que vous avez encore des choses à investiguer voire documenter ?

**Comment by spelhate** [comment]
On peut fermer si @jeanpommier  est d'accord.

**Comment by jeanpommier** [comment]
Yep, no problemo
Merci !
