### ISSUE TITLE
identification des fichiers de config mviewer

### ISSUE THREAD

**Issue by jeanpommier** [geobretagne/mviewerstudio#55]
Bonjour,
A moins que quelque chose ne m'ait échappé, pour l'instant, quand on sauvegarde une config mviewer, elle est stockée dans un dossier (par défaut apps/store) avec un [uuid].xml. Toutes les configs sont sauvées en vrac, sans moyen facile d'idntifier qui est quoi et a été créé par qui.

Ca pourrait être bien d'avoir la possibilité de choisir le nom à donner au fichier : en l'état, mviewerstudio ne permet pas de tout faire (par exemple des templates mustache). Du coup, lorsqu'on veut éditer le fichier, c'est sympa si le nom est plus human-friendly.

Dans la même idée, ce serait bien de pouvoir "faire le ménage" de façon sélective : supprimer certaines sauvegardes mais pas toutes. Et écraser une config qu'on vient de mettre à jour

Peut-être qu'on pourrait aussi sauver les fichiers dans des sous-répertoires au nom de leur propriétaire, s'il est identifié.

Qu'en dites-vous ?

**Comment by bchartier** [comment]
> A moins que quelque chose ne m'ait échappé, pour l'instant, quand on sauvegarde une config mviewer, elle est stockée dans un dossier (par défaut apps/store) avec un [uuid].xml. Toutes les configs sont sauvées en vrac, sans moyen facile d'idntifier qui est quoi et a été créé par qui.

> Peut-être qu'on pourrait aussi sauver les fichiers dans des sous-répertoires au nom de leur propriétaire, s'il est identifié.

Tu as raison.
C'est la raison pour laquelle tu as vu passer data.userGroups (mentionné là #52).
Dans le backend alternatif que nous avons réalisé à Neogeo nous utilisons la notion abstraite de groupe pour organiser les fichiers XML sur le serveur en sous-répertoires et pour faciliter la recherche. De mémoire, quand cette notion est présente un filtre apparaît dans la fenêtre d'ouverture d'une carte qui permet d'appliquer une sélection sur un groupe particulier.

Voici à quoi cela ressemble :
![IDéO_BFC_-_studio_carto](https://user-images.githubusercontent.com/2361255/74420714-30b6f880-4e4c-11ea-9834-67a74435e49e.jpg)

Au niveau de notre backend nous utilisons la notion abstraite de groupe pour représenter la notion plus concrète d' organisation à laquelle l'utilisateur est attaché (il peut être attaché à plusieurs organisations chez nous d'ailleurs). Pour chaque groupe/organisation nous créons un répertoire dans lequel on va trouver toutes les cartes du groupe/organisation. On pourrait imaginer qu'un autre backend utilise cela plutôt pour des groupes thématiques/des groupes de travail plutôt que des organisations.

> Ca pourrait être bien d'avoir la possibilité de choisir le nom à donner au fichier : en l'état, mviewerstudio ne permet pas de tout faire (par exemple des templates mustache). Du coup, lorsqu'on veut éditer le fichier, c'est sympa si le nom est plus human-friendly.

Je n'ai été voir dans le code pour savoir si c'est le backend ou le client qui choisit les noms des fichiers créés. Je donne un exemple de ce que nous faisons de notre côté :
`neogeo-technologies/test-seb-2.xml`
On a le nom du répertoire qui est le nom de l'organisation qui a créée le fichier et le nom de la carte. Les deux sont les noms en langage naturel mais slugifiés. Mais c'est peut-être une spécificité de notre backend (qui pourrait être reprise dans celui proposé par Camptocamp).
C'est vrai que cela pourrait être utile que le nom du fichier soit éditable.

> Dans la même idée, ce serait bien de pouvoir "faire le ménage" de façon sélective : supprimer certaines sauvegardes mais pas toutes.

Oui, je crois que tout le monde en a besoin. Après il faudrait sûrement que ce soit limité aux cartes de l'utilisateur courant ou à celles de son organisation.

> Et écraser une config qu'on vient de mettre à jour

Chez nous on fait ça il me semble. Sauf dans un cas particulier : lorsqu'une carte est ouverte en édition par un utilisateur qui travaille pour une autre organisation que celle qui a créé la carte. Dans ce cas la modification apportée à la carte est sauvegardée dans le répertoire de l'organisation de l'utilisateur qui fait la modif.

Autre réflexion que je me suis faite il y a quelques jours : ce serait peut-être bien de gérer une espèce d'état des cartes pour pouvoir faciliter la recherche et la gestion. Genre un état "brouillon", "publié", "obsolète"... que l'on mettrait dans les métadonnées Dublin Core du fichier.

Désolé de prendre à chaque fois des références sur un backend que personne d'autre que nous utilise. Mais comme la question de la modernisation du backend de mviewerstudio est posée autant en profiter.

**Comment by jeanpommier** [comment]
Merci @bchartier pour cette contribution. J'ai une question par rapport à votre backend : est-il open source, ou bien privé ? Je ne l'ai pas trouvé sur github.

Perso, je me fiche assez de savoir quel backend j'utilise, php, C2C ou Neogeo. Je trouve intéressant de mettre en commun les besoins et essayer de se mettre d'accord sur la structure des services pouvant être consommés par le frontend, si celui-ci doit rester commun. Si chacun bricole dans son coin, le frontend va vite devenir un cauchemar à entretenir, non ? Cf. le dernier épisode de #52...

Pour éviter ce genre de surprise, il me semble qu'il faudrait commencer à documenter une API que puisse suivre chaque backend, qu'on dispose d'un endroit unique listant les services que mviewerstudio frontend sait consommer.

**Comment by bchartier** [comment]
> Merci @bchartier pour cette contribution. J'ai une question par rapport à votre backend : est-il open source, ou bien privé ? Je ne l'ai pas trouvé sur github.

Il est public mais son nom est peut-être pourri.
https://github.com/neogeo-technologies/idgo-mviewerstudio-proxy
On aura peut-être intérêt à changer son nom.
Après je pense que son code pourrait bénéficier d'un toilettage ou d'une mise à niveau, voire d'une documentation.

> Perso, je me fiche assez de savoir quel backend j'utilise, php, C2C ou Neogeo. Je trouve intéressant de mettre en commun les besoins et essayer de se mettre d'accord sur la structure des services pouvant être consommés par le frontend, si celui-ci doit rester commun. Si chacun bricole dans son coin, le frontend va vite devenir un cauchemar à entretenir, non ? Cf. le dernier épisode de #52...

Bah, oui et non. On a fait un gros effort sur mviewerstudio pour éviter trop de sépcificités.

> Pour éviter ce genre de surprise, il me semble qu'il faudrait commencer à documenter une API que puisse suivre chaque backend, qu'on dispose d'un endroit unique listant les services que mviewerstudio frontend sait consommer.

Oui, tu as raison il manque une documentation de certains aspects de l'appli. Cette API entre le front et la back fait sans aucun doute partie de ces aspects manquants. Mais c'est difficile de dégager des moyens pour cela.

**Comment by bchartier** [comment]
@jeanpommier :
je reviens vers ton expression de besoin initiale :
- la description de l'interface actuelle entre le frontend et le backend a fait l'objet d'une première description là : https://github.com/geobretagne/mviewerstudio/blob/master/srv/README.md
- cette interface fait l'objet d'une discussion et de premiers changements décrits là : #52.
- faire le ménage de façon sélective : oui. Il faudrait définir l'interface entre le backend et le frontend pour cela : est-ce que l'on utilise le point d'accès existant (delete) en y passant les références aux fichiers à supprimer ou est-ce qu'on définit un autre point d'accès dédié -> là il faudrait faire un ticket spécifique pour cela.
- écrire le fichier XML produit dans le répertoire de l'utilisateur ou de son organisation est tout à fait possible et souhaitable à mon avis.

**Comment by jeanpommier** [comment]
@bchartier 
Merci.
Je n'ai pas été très actif sur ces fils ces derniers jours, mais j'ai suivi avec intérêt. Merci pour ta réactivité et ton soutien sur ce sujet. C'est important, tout ça, si on veut toucher un public plus large.

De mon côté, je vais remettre un coup sur l'aspect i18n, il faudrait que je finisse au moins la version anglaise.

**Comment by bchartier** [comment]
@jeanpommier  : quelle suite donner à ce ticket ? Je ferme ou est-ce qu'il y a une demande d'évolution à étudier ?

**Comment by jeanpommier** [comment]
Pour ma part, tu peux fermer. Au final, j'utilise assez peu mviewerstudio, j'avoue
