### ISSUE TITLE
Création d'une thématique de deuxème niveau ?

### ISSUE THREAD

**Issue by jerbou** [geobretagne/mviewerstudio#58]
Bonjour,

Je débute avec Mviewer Studio, et est-il possible de créer un deuxième niveau dans une thématique ?
Comme sur https://kartenn.region-bretagne.fr/kartenn/ mais avec un paramétrage dans l'interface graphique ?
La thématique découapges territoriaux, présente un sous thématique Limites administratives.
Ou est-ce que c'est de l'édition du fichier xml ?

Merci,
J. Boutet

**Comment by spelhate** [comment]
Bonjour. Actuellement ce paramétrage n'est pas disponible dans l'interface du studio. Il faut donc passer par une édition manuelle du fichier de configuration xml.

**Comment by jerbou** [comment]
Ok, merci Sébastien.

Est-ce qu'il y a des fichiers exemples publics de configurations xml qui présentent ces "sous thématiques", histoire de regarde, d'apprendre à s'en servir ?

**Comment by spelhate** [comment]
Exemple d'utilisation de sous-thématiques

Démo : https://kartenn.region-bretagne.fr/territoires/?topics=transport

Configuration : https://github.com/region-bretagne/mviewer-apps/blob/master/territoire/territoire.xml#L532

**Comment by jerbou** [comment]
Merci beaucoup !
