### ISSUE TITLE
Configuration et mviewer_short_url

### ISSUE THREAD

**Issue by Gaetanbrl** [geobretagne/mviewerstudio#59]
J'ai un Mviewer nommé "mviewerbzh" avec un dossier "mviewerbzh/apps"  de façon très classique.

J'ai modifié la configuration telle que : 

```
        "upload_service": "srv/store.php",
        "mviewer_instance": "http://localhost/mviewerbzh/",
        "conf_path_from_mviewer" :"../mviewerbzh/apps/",
        "mviewer_short_url": {
            "used": true,
            "apps_folder": ""
        },
        "external_themes": {
            "used": false,
            "url": "https://geobretagne.fr/minicatalog/csv"
        },
        "user_info": "srv/user_info.php",
        "export_conf_folder" : "C:/xampp/htdocs/mviewerbzh/apps/",
```

* "prévisualiser" fonctionne.
* "Sauvegarder" fonctionne.
* "Télécharger" fonctionne.

Mais le raccourci est KO. Je ne peux pas générer de lien.

En effet le lien est du type : 
`http://localhost/mviewerbzh/7147f96e2b42b1e578d154d86f2be40e`

Hors, le fichier de configuraiton devrait être dans mviewerbzh/apps/

Je change alors le paramètre `mviewer_short_url` de la sorte : 
```
        "mviewer_short_url": {
            "used": true,
            "apps_folder": "apps"
        },
```

Et là mon bouton "prévisualiser" ne fonctionne plus. J'ai une URL qui est bonne mais une erreure dans la console qui n'est pas cohérente : 
* URL navigateur 
http://localhost/mviewerbzh/#apps/a39990f59b2d4639db64130421a326a0

* URL erreur dans la console : 
http://localhost/mviewerbzh/apps/apps/a39990f59b2d4639db64130421a326a0.xml?_dc=1583858994237

Pourquoi le "mviewer_sort_url" me rajoute un `apps/apps` pour récupérer le fichier de config ? 

Mon fichier est pourtant bien dans mviewerbzh/apps.

**Comment by spelhate** [comment]
et dans la config, si tu mets :
 `conf_path_from_mviewer:"../mviewerbzh/"` 
à la place de :
`conf_path_from_mviewer:"../mviewerbzh/apps/"`

**Comment by Gaetanbrl** [comment]
Ok Merci @spelhate ca fonctionne.
Je sais pas ce que j'ai fichu, je pensais avoir testé cette conf également...

Merci je clos.
