### ISSUE TITLE
Branch develop

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#61]
Je propose de créer une branche develop dans ce projet de manière similaire à ce qui a été fait pour mviewer :
- branche master : versions officielles (bénéficiant de releases) que les utilisateurs peuvent télécharger de manière assez sereine
- branche develop : lieu d'injection des nouvelles fonctions et corrections avant intégration dans une release officielle

C'est plus pour information qu'une réelle question... ;)

**Comment by bchartier** [comment]
Voilà c'est fait :
https://github.com/geobretagne/mviewerstudio/tree/develop

**Comment by bchartier** [comment]
J'en ai profité pour créer les mêmes labels d'issues que pour le projet mviewer.

**Comment by spelhate** [comment]
Merci @bchartier
