### ISSUE TITLE
Désactivation des fonctions/options non réellement opérationnelles

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#62]
Je propose de retirer de l'IHM de mviewerstudio les fonctions/options qui ne sont pas implémentées dans mviewerstudio car cela perturbe les nouveaux utilisateurs qui s'imaginent que mviewerstudio a des capacités qu'il n'a pas (dans un premier temps) et qu'il est défectueux (dans un second temps). Tout cela provoque de la déception alors que l'on peut éviter cela.

En l'occurence, dans la popup présentant le détail d'une couche :
- désactiver la possibilité de pouvoir choisir autre chose que "WMS" comme type de couche. Aujourd'hui mviewerstudio ne sait configurer qu'une couche WMS
- désactiver la possibilité d'activer la recherche fuse car elle n'est applicable qu'à des couches vecteurs et non des couches WMS

Qu'en pensez-vous ?

**Comment by spelhate** [comment]
Pour info, ces options ont été introduites dès le départ dans mviewerstudio avec pour objectif principal de donner l'idée, voire l'envie à de gentils développeurs d'implémenter ces fonctionnalités et de montrer le studio tel qu'il est, c'est à dire un projet bien amorcé mais encore inachevé. Force est de constater que ça n'a pas fonctionné.
Je dit donc oui pour retirer ces options non fonctionnelles en espérant les voir revenir un jour...

**Comment by bchartier** [comment]
J'espère aussi que cela pourra arriver.

**Comment by RemiDesgrange** [comment]
Sinon on ajoute une petite icone "beta" dans la navbar :stuck_out_tongue:

**Comment by bchartier** [comment]
Côté intégré à develop.
Je ferme.
