### ISSUE TITLE
Messages de log

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#63]
Je me suis lancé dans le nettoyage des messages de log dans la partie frontend de mviewerstudio.
On a pas mal de logs plutôt à destination des développeurs dans les parties du code qui chargent une config XML.
**Je propose d'utiliser des console.groupCollapsed** pour grouper et rendre moins visibles ces messages qui pourraient être anxiogènes pour des gens qui ne connaissent pas le code.
Genre :
```
        parseApplication(xml) {
            console.groupCollapsed("parseApplication");
[...]
            console.groupEnd("parseApplication");
```

`parseApplication` est le nom de la fonction qui lit le fichier de configuration XML de mviewer.

Pour donner :
![DevTools_-_0_0_0_0_8084__xml_temp_config-sample_xml](https://user-images.githubusercontent.com/2361255/77244243-3655ea00-6c13-11ea-8de9-a7592662b860.jpg)

Et lorsque l'utilisateur déplie le groupe :
![DevTools_-_0_0_0_0_8084__xml_temp_config-sample_xml](https://user-images.githubusercontent.com/2361255/77244257-51285e80-6c13-11ea-9dc7-8db60c3086a6.jpg)

**Est-ce que vous avez une objection à cela ?**

**Comment by RemiDesgrange** [comment]
Ne pourrait t'on pas faire des `console.log` (ou `groupCollapsed`) et via une config, désactiver en prod , je ne connais que le monkey patching de `console.log`  et consort pour ça par contre.

**Comment by bchartier** [comment]
Oui, on pourrait faire ce genre de chose. Je pense qu'on doit pouvoir trouver des bibliothèques qui font le job. J'ai recherché cela avant de poster ce ticket mais on trouve surtout des truc qui tournent autour de Node pour des dev côté serveur.

Ceci dit, je pense que la plupart des logs existants (pas tous - je suis en train de faire le ménage sur une branche locale) peuvent être utiles quand on a besoin de diagnostiquer le problème d'un utilisateur. Je pense qu'on doit s'efforcer de mettre des logs pertinents pour la prod et éventuellement de masquer leur complexité au premier abord. Je propose donc de faire déjà des logs propres et ensuite si on sent que ce n'est pas suffisant on regardera si on peut désactiver certains logs quand on est en prod.

Approche progressive si nécessaire en somme.

**Comment by bchartier** [comment]
Pour préciser ce que je suis en train de faire dans ma branche locale :
- voir pour l'utilisation des groupCollapsed
- utilisation de l'anglais dans tous les messages de log
- utilisation de console.error et console.warn lorsqu'il s'agit d'erreurs ou d'avertissements (je n'ai pas encore trouvé de cas d'avertissement)
- suppression des logs qui correspondaient visiblement à des tests et qui n'ont plus lieu d'être
