### ISSUE TITLE
Configuration du proxy

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#7]
Je souhaite rendre l'url du proxy configurable dans le fichier config.json.
Mais je me rends compte que je ne comprends pas bien la manière dont ça fonctionne actuellement.
J'allais remplacer cette ligne : 
https://github.com/geobretagne/mviewerstudio/blob/master/js/mviewerstudio.js#L10
par une lecture du fichier de config.
Si le paramètre est absent, hop on utilise la valeur par défaut présente dans le code : "../proxy/?url=" (pour une question de compatibilité des fichiers config.json de mviewerstudio qui peuvent trainer à droite et à gauche).
Si le paramètre est défini mais avec une chaîne vide, je ne change pas l'URL en ajoutant un cas là :
https://github.com/geobretagne/mviewerstudio/blob/master/lib/mv.js#L734

Mais voilà, je me rends compte qu'il y a une autre référence à un proxy qui traine dans le code :
https://github.com/geobretagne/mviewerstudio/blob/master/lib/mv.js#L779

Qu'est-ce que ça fait là ? Pourquoi ne pas utiliser ce qui est présent dans _conf.proxy ?

**Comment by spelhate** [comment]
Tu as raison @bchartier, il faut prendre en compte le paramètre proxy du fichier de configuration.
L'autre référence au proxy dont tu parles concerne en fait le paramètre proxy de l'application mviewer qui est stocké dans le fichier de config.xml

**Comment by bchartier** [comment]
ok, je n'avais pas vu qu'il s'agissait du fichier config.xml de l'application mviewer.
Merci.

**Comment by bchartier** [comment]
@spelhate : rendre l'URL du proxy configurable ne te dérange pas ?

**Comment by spelhate** [comment]
Oui je suis pour rendre l'URL du proxy configurable

**Comment by bchartier** [comment]
Fait via #9
