### ISSUE TITLE
Intégrer un SLD local

### ISSUE THREAD

**Issue by RemiDesgrange** [geobretagne/mviewerstudio#78]
Il est actuellement possible d'intégrer un SLD via une URL dans mviewer, on pourrait faire un formulaire de chargement de SLD qui serait alors accessible via l'URL `https://votre_mviewer/apps/styles/monstyle.sld`. 

Quelque chose comme ceci : 
![image](https://user-images.githubusercontent.com/13271765/83139977-8fe40480-a0ed-11ea-8087-f8edc5e92a25.png)

J'envisage de mettre une tooltips pour que ce soit plus parlant.

### Liste des tâches

- [ ] ajouter un bouton  pour le chargement de SLD ;
- [ ] ajouter un endpoint pour sauvegarder le fichier correctement. Le SLD aura un nom aléatoire pour éviter les clash de nom ;
    - [ ] dans le backend python ;
    - [ ] dans le backend php ;
- [ ] ajouter le SLD chargé dans la config en cours

**Comment by Gaetanbrl** [comment]
Actuellement on peut en effet préciser un style (nom du SLD) disponible sur le GeoServer ou une URL. 

Il peut y avoir plusieurs ressources de précisées (séparateur ","). Ce qui permet d'afficher la liste "Analyse" dans le Mviewer et jongler avec les styles de couche.

Aussi, sur ton image tu mets "SLD externe", ce qui n'est plus le cas s'il est sauvegardé.
Une interface type "radio" permettra peut-être de simplement l'intégrer en local ou préciser que c'est un SLD cette fois bien externe.

Il faudrait également préciser dans les labels autre chose que `SLD`. Le Mviewer étant accès tout public et SLD étant surtout connu par les personnes connaissant (+/-) les SIG.

Quelque chose comme "Fichier de style (sld)" pour le titre et "Charger un fichier" serait peut être plus approprié pour l'utilisateur final.

**Comment by fvanderbiest** [comment]
>￼ dans le backend php ;

Je me pose la question de la pertinence de conserver 2 backends et du travail à double que cela implique. Quel serait votre avis sur ce point ?

**Comment by pierrejego** [comment]
Pour moi il faut conserver la backend php, c'est beaucoup plus simple à déployer pour des néophytes ou des windowsien (sisi il y a en a plus qu'on pense :))

**Comment by RemiDesgrange** [comment]
Je clos car la PR a été mergé.
