### ISSUE TITLE
Redimensionnement incontrôlé de la carte

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#8]
Lorsque l'on redimensionne légèrement la largeur de la fenêtre du navigateur, la hauteur de la carte sur la page d'accueil de mviewer studio augmente. Plus on touche à la largeur de la fenêtre, plus la hauteur de la carte devient importante. C'est étonnant.

**Comment by spelhate** [comment]
Vu. On peut corriger en ajoutant une propriété css du type : 
#map {
    max-height: 350px;
}

**Comment by bchartier** [comment]
Ok, je regarderai cela.

**Comment by bchartier** [comment]
La correction est présente dans le pullrequest #13
