### ISSUE TITLE
Requête CSW GetRecords en défaut avec une version récente de GeoNetwork

### ISSUE THREAD

**Issue by bchartier** [geobretagne/mviewerstudio#81]
La Région Hauts-de-France m'a signalé un problème avec la recherche de mviewerstudio sur un catalogue CSW : les requêtes donnent systématiquement un résultat vide avec leur catalogue GeoNetwork (version récente de geOrchestra).

J'ai identifié deux soucis :
* seule la première occurence de la chaîne {query} est remplacée par le texte saisi par l'utilisateur
* la forme du filtre de  cette requête (imbrication de <ogc:Or> et <ogc:And>) est considérée comme invalide par ce catalogue. Pourtant cela fonctionne avec le catalogue actuel de GéoBretagne. Ceci dit, l'erreur est probablement justifiée car après analyse le truc est beaucoup trop complexe pour être honnête.

Je prépare un pull request pour corriger ces deux points.

**Comment by bchartier** [comment]
J'ai mergé la pull request après avoir testé sur le catalogue de la plateforme Géo2France.

**Comment by bchartier** [comment]
@vfabry : est-ce que je peux fermer ce ticket ?

**Comment by vfabry** [comment]
oui.

**Comment by bchartier** [comment]
Merci.
