### ISSUE TITLE
accès en écriture au répertoire des scripts php

### ISSUE THREAD

**Issue by vfabry** [geobretagne/mviewerstudio#85]
> upload_service : Service web utilisé pour stocker les configurations mviewer créées avec le générateur. Valeur par défaut : srv/store.php. Ne pas oublier d'autoriser l'utilisateur apache à accéder en écriture au répertoire

Histoire de faire la bonne demande à mon administrateur système, c'est à quel utilisateur qu'on doit donner les droits ?

Merci !
Vincent
PS : @bchartier : c'est pour une install sur un serveur région

**Comment by Gaetanbrl** [comment]
Ca dépendra de votre environnement je pense, il faut justement demander à l'admin sys de faire en sorte que l'utilisateur apache (www-data, apache, autre...) puisse déposer dans ce répertoire. Le nom de l'utilisateur peut varier en fonction des installation.

Vous aurez probablement plus de réponse en contactant les personnes en charge de l'installation de votre environnement.

**Comment by spelhate** [comment]
Dans notre environnement linux, nous utilisons Apache2 et le backend php.
C'est l'utilisateur www-data qui doit disposer des droits d'écriture sur le répertoire dans lequel sont stockées les applications.

**Comment by vfabry** [comment]
Merci pour vos réponses !
Vincent
