### ISSUE TITLE
WMTS matrixset spécifique

### ISSUE THREAD

**Issue by RemiDesgrange** [geobretagne/mviewerstudio#92]
Bonjour,

Je suis en train de vouloir intégrer une couche de fond du CRAIG (libre) => https://tiles.craig.fr/ortho/service?service=WMTS&request=GetCapabilities (couche ortho_2016).

Le matrixset est "webmercator". J'ai mis la configuration suivante dans le fichier de config:
```json
"ortho2016craig": {
    "id": "ortho2016craig",
    "thumbgallery": "img/basemap/ortho.jpg",
    "title": "CRAIG-ORTHO",
    "label": "Photo aerienne actuelle",
    "type": "WMTS",
    "url": "https://tiles.craig.fr/ortho/service",
    "layers": "ortho_2016",
    "format": "image/png",
    "style": "default",
    "matrixset": "webmercator",
    "fromcapacity": "false",
    "attribution": "CRAIG-IGN / BDORTHO"
}
```

Dans mviewer j'ai une erreur lors du lookup du matrix ID et résolution : https://github.com/geobretagne/mviewer/blob/develop/js/mviewer.js#L1048-L1051

Je ne sais pas si c'est moi où alors mviewer/mviewerstudio n'est pas capable d'interpréter les couches avec des matrixset autre que des descriptions EPSG ?

**Comment by Gaetanbrl** [comment]
> J'ai mis la configuration suivante dans le fichier de config

As tu le fichier de config à partager ?

**Comment by Gaetanbrl** [comment]
Juste comme ca, j'ai un doute tu parles bien du fichier de config xml ?

**Comment by RemiDesgrange** [comment]
C'est un bug mviewer et mviewer studio je pense :-)

Je viens d'en discuter avec Landry du CRAIG et il semble que le bug vienne bien de mviewer. Dans QGIS ça fonctionne super bien.

Plutôt que de faire un guess sur les properties, on pourrait demander mettre le liens vers le GetCap et le parser (comme là https://openlayers.org/en/latest/examples/wms-capabilities.html).
Dans un premier temps peut-être juste rajouter des propriétés avec des valeurs par défaut.

**Comment by RemiDesgrange** [comment]
Je ne sais pas ce qu'en pense @spelhate et @bchartier Si on voulait corriger le bug complètement, on pourrait effectivement faire appel au getcapabilities et laisser openlayers se débrouiller et faire sa "tambouile".

**Comment by bchartier** [comment]
Oui, on pourrait améliorer cela.

**Comment by Gaetanbrl** [comment]
Une petite question @RemiDesgrange, ce n'est pas le cas avec ce paramètre ? 

https://github.com/geobretagne/mviewer/blob/2d9810009768868f2adf0e174782a69ea0abc60d/js/mviewer.js#L1035

**Comment by RemiDesgrange** [comment]
OH! bien joué  @Gaetanbrl

**Comment by Gaetanbrl** [comment]
Redis nous si ca convient bien pour l'intégration du WMTS du Craig.

**Comment by RemiDesgrange** [comment]
C'est ok
